/**
 * Flight Booking App.
 * Node Version 20.7.9.
 * React Version 18
 * Next Version 14.0.3
 */
"use client";

import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

// from mui
import Box from "@mui/material/Box";
import Card from "@mui/material/Card";
import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";
import Dashboard from "./dashboard/index";
import ProtectedRoute from "./components/ProtectedRoute";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <ProtectedRoute>
      <Head>
        <title>Flight Booking App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className={`${styles.main} ${inter.className}`}> */}
      <main>
        <Dashboard />
      </main>
    </ProtectedRoute>
  );
}
